FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ./SampleWebApp.sln ./
COPY ./SampleWebApp/SampleWebApp.csproj ./SampleWebApp/
#COPY ./TestProj/TestProj.csproj ./TestProj/
RUN dotnet restore
COPY . .
#RUN dotnet test ./TestProj/TestProj.csproj
RUN dotnet publish ./SampleWebApp/SampleWebApp.csproj -c Release -o /app/

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS final
WORKDIR /app
COPY --from=build /app .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "SampleWebApp.dll"]
