FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
COPY ./SerilogDemoApp.sln ./
COPY ./SerilogDemo/SerilogDemo.csproj ./SerilogDemo/
RUN dotnet restore
COPY . .
RUN dotnet publish ./SerilogDemo/SerilogDemo.csproj -c Release -o /app/

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS final
WORKDIR /app
COPY --from=build /app .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "SerilogDemo.dll"]